In [104]:
import pandas as pd
import numpy as np

In [150]:
df = pd.read_csv(r'D:\Salzburg\Study1\P01\P01_treadmill\20221205_P01_UB_up_8.csv', sep=';', header=None)

In [151]:
idx_imu = df[df[0]=='Devices'].index[0]
idx_force = df[df[0]=='Devices'].index[1]
idx_marker = df[df[0]=='Trajectories'].index[0]

In [161]:
df_imu = df[idx_imu:idx_force]
df_force = df[idx_force:idx_marker]
df_marker = df[idx_marker:]

In [153]:
fs_imu = int(df_imu.iloc[1])
fs_force = int(df_force.iloc[1])
fs_marker = int(df_marker.iloc[1])

In [138]:
def df_reshape_analog(df):
    cols = df.iloc[3].values[0].split(',')[2:]
    df = df[0].str.split(',',expand=True).iloc[5:,2:-1]
    df.columns=cols
    df.reset_index(drop=True, inplace=True)
    return df.astype('float64')

In [139]:
def df_reshape_marker(df_in):
    markers = [name[4:] for name in df_in.iloc[2].values[0].replace(',,', '').split(',')[:-1]]
    cols = [np.repeat(markers, 3), np.tile(['x', 'y', 'z'], len(markers))]
    df_out = df_in[0].str.split(',',expand=True).iloc[5:,2:-1]
    df_out.columns=cols
    df_out.reset_index(drop=True, inplace=True)
    return df_out.astype('float64')

In [162]:
markers = [name[4:] for name in df_marker.iloc[2].values[0].replace(',,', '').split(',')[:-1]]
cols = [np.repeat(markers, 3), np.tile(['x', 'y', 'z'], len(markers))]
df_marker = df_marker[0].str.split(',',expand=True).iloc[5:,2:-1]
df_marker.columns=cols

In [164]:
df_marker.reset_index(drop=True, inplace=True)

In [173]:
df_marker.apply(lambda x: pd.to_numeric(x, errors='coerce'))

            RMTPM                              RToeM                         \
                x           y          z           x           y          z
0      849.491760  528.653015  53.633789  894.104919  516.275513  55.105679
1      839.185242  529.507507  54.567215  884.642151  516.298157  55.418484
2      827.942627  529.764832  55.055912  873.339233  516.783447  54.729759
3      818.266907  528.055725  57.133438  862.048706  516.244629  55.065811
4      808.111511  527.859436  58.771481  851.502869  514.186035  54.973362
...           ...         ...        ...         ...         ...        ...
11995  890.613953  506.844055  70.973686  933.760681  489.462158  61.090012
11996  880.741333  505.661560  73.618515  923.422363  488.462036  61.862671
11997  871.546997  504.989990  76.497520  913.447205  487.893463  62.554024
11998  862.960022  504.630157  80.077759  904.488464  487.534607  63.766846
11999  853.822876  503.937897  83.212387  894.850769  486.602844  65.215240

            RToe2                              RToeL  ...       LToe2  \
                x           y          z           x  ...           z
0      915.364990  476.382599  68.464523  863.772461  ...  121.733284
1      904.271790  476.094971  67.944717  852.634521  ...  119.371826
2      893.371948  475.700287  67.518501  841.942688  ...  116.877647
3      882.398376  475.318207  66.953186  831.045837  ...  114.125221
4      871.622742  475.517090  65.805077  819.972778  ...  112.063019
...           ...         ...        ...         ...  ...         ...
11995  951.889954  447.182648  69.212997  895.567200  ...  111.612282
11996  941.806152  446.831390  68.585052  885.086487  ...  110.908997
11997  931.903809  446.075378  67.844017  874.757080  ...  110.670219
11998  922.302612  445.075592  67.045776  864.777161  ...  110.995903
11999  913.091003  444.095245  66.109589  854.804321  ...  111.958908

             LToeL                                LMTPL              \
                 x           y           z            x           y
0       909.127991  671.760559  137.647400   866.427368  680.962830
1       927.075500  671.232239  133.370148   882.572144  680.559509
2       945.859497  670.527039  129.748825   899.759644  680.261841
3       964.383850  670.223022  125.915619   917.090271  679.781433
4       983.009399  669.854614  122.192780   934.608704  679.230408
...            ...         ...         ...          ...         ...
11995  1190.122681  643.827515  114.435966  1139.110718  654.473633
11996  1209.602905  642.323303  111.757553  1157.522705  652.848572
11997  1229.193481  640.468628  109.371277  1176.705200  650.719727
11998  1248.465820  638.641846  107.446404  1195.667725  648.782104
11999  1267.586060  636.694946  105.978996  1214.617554  646.672241

                         IMULF
                z            x           y           z
0      167.389420   930.005981  626.270874  221.117264
1      160.965256   944.778748  625.732849  217.544403
2      155.219116   959.974731  625.174805  214.100296
3      149.515030   975.115356  624.773621  210.660461
4      143.892349   990.371216  624.300415  207.196030
...           ...          ...         ...         ...
11995  127.419380  1180.104492  598.106567  198.422577
11996  122.336639  1196.146240  596.896423  195.312607
11997  117.523827  1212.024048  595.444885  192.562256
11998  113.188927  1227.984741  594.636780  190.272873
11999  109.300171  1243.536865  593.373535  188.132751

[12000 rows x 177 columns]

In [140]:
imu = df_reshape_analog(df_imu)

In [141]:
imu.iloc[:,:len(imu.columns)//2]/1000

,IMU1_ACC_X,IMU1_ACC_Y,IMU1_ACC_Z,IMU2_ACC_X,IMU2_ACC_Y,IMU2_ACC_Z,IMU3_ACC_X,IMU3_ACC_Y,IMU3_ACC_Z,IMU4_ACC_X,...,IMU13_ACC_Z,IMU14_ACC_X,IMU14_ACC_Y,IMU14_ACC_Z,IMU15_ACC_X,IMU15_ACC_Y,IMU15_ACC_Z,IMU16_ACC_X,IMU16_ACC_Y,IMU16_ACC_Z
0,0.009982,-0.091415,9.86216,-0.006799,-0.061437,9.72213,-0.011992,0.051085,9.92526,0.042276,...,9.89250,-13.30190,-1.198740,30.2479,-3.76452,-20.71960,23.2881,0.032760,0.035139,9.86453
1,0.010632,-0.092066,9.85305,-0.010051,-0.052332,9.73449,-0.015893,0.048483,9.92526,0.033171,...,9.88600,-13.57240,-1.099890,30.1204,-3.72485,-20.25010,23.4481,0.039263,0.037740,9.85153
2,0.011283,-0.092716,9.84395,-0.013303,-0.043228,9.74684,-0.019795,0.045882,9.92526,0.024067,...,9.87950,-13.84290,-1.001040,29.9930,-3.68518,-19.78060,23.6081,0.045766,0.040341,9.83852
3,0.011933,-0.093366,9.83484,-0.016554,-0.034123,9.75920,-0.023697,0.043281,9.92526,0.014963,...,9.87299,-14.11350,-0.902193,29.8655,-3.64552,-19.31100,23.7681,0.052269,0.042943,9.82552
4,0.012584,-0.094017,9.82574,-0.019806,-0.025019,9.77155,-0.027599,0.040680,9.92526,0.005858,...,9.86649,-14.38400,-0.803345,29.7381,-3.60585,-18.84150,23.9281,0.058772,0.045544,9.81251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,0.037740,-0.123196,9.79635,0.031926,-0.002860,9.82939,0.014533,0.032601,9.83609,-0.017137,...,9.86467,-3.50737,-0.762940,31.6022,-25.24710,-5.81292,13.2761,-0.028648,0.032694,9.78744
119996,0.030552,-0.125107,9.79412,0.040415,0.001933,9.80711,0.019603,0.040738,9.85736,-0.025442,...,9.87217,-3.44712,-0.825495,31.5669,-24.82360,-6.31110,13.1474,-0.046096,0.029425,9.78534
119997,0.033432,-0.117178,9.78288,0.038421,0.005682,9.79292,0.016254,0.044334,9.87670,-0.028179,...,9.87145,-3.64705,-0.857873,31.3645,-24.23170,-6.85809,13.0389,-0.064288,0.031087,9.78100
119998,0.043837,-0.104822,9.76987,0.028016,0.006332,9.79422,0.007149,0.041733,9.88320,-0.024278,...,9.86364,-3.96960,-0.844216,31.1258,-23.82530,-7.13643,13.0109,-0.072742,0.036289,9.77709
119999,0.054242,-0.092466,9.75687,0.017610,0.006983,9.79552,-0.001955,0.039131,9.88971,-0.020376,...,9.85584,-4.29216,-0.830559,30.8872,-23.41880,-7.41476,12.9829,-0.081196,0.041492,9.77319

In [148]:
def df_reshape_analog(df):
    cols = df.iloc[3].values[0].split(',')[6:]
    df = df[0].str.split(',',expand=True).iloc[5:,6:-1]
    df.columns=cols
    df.reset_index(drop=True, inplace=True)
    return df

In [149]:
df_reshape_analog(df_force)

,Fx,Fy,Fz,Mx,My,Mz,Cx,Cy,Cz,Pin 1,Pin 2,Pin 3,Pin 4,Pin 5,Pin 6,Pin 7,Pin 8
0,-152.351,-72.0652,-597.091,-39582.1,-239277,-19623.6,904.262,591.292,0,5.00702,4.54315,4.74548,4.39758,2.12982,1.9342,1.49353,1.46484
1,-154.078,-71.3253,-570.878,-38729.9,-237253,-18518.2,889.407,592.843,0,5.00488,4.55017,4.74213,4.38995,2.10144,1.91589,1.47125,1.44775
2,-153.093,-66.2172,-548.865,-36838.7,-232218,-14843.7,881.913,592.118,0,5.01434,4.57916,4.75189,4.38599,2.07336,1.89697,1.45691,1.43677
3,-149.347,-58.171,-528.992,-36044.2,-224053,-9201.43,881.452,593.138,0,5.03082,4.62372,4.77417,4.3866,2.04498,1.87439,1.44409,1.43524
4,-144.464,-47.7781,-507.26,-35417.9,-214622,-3034.13,881.899,594.822,0,5.05768,4.6759,4.80103,4.38965,2.01385,1.84845,1.42944,1.43555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,-85.5571,-45.3774,-1418.9,1251.53,-322610,-9447.27,1077.63,524.118,0,5.08972,4.68872,4.93225,4.63196,2.7887,2.77618,2.1167,2.04071
59996,-89.0689,-41.7016,-1401.51,1652.12,-322983,-14635.3,1074.55,523.821,0,5.12451,4.68201,4.90295,4.63959,2.77588,2.76245,2.10083,2.02606
59997,-95.9225,-35.8839,-1375.96,4226.32,-321568,-18163,1071.3,521.928,0,5.16632,4.68445,4.86969,4.63043,2.75116,2.74475,2.0813,2.00409
59998,-104.496,-28.0924,-1352.7,5304.74,-324380,-19420.3,1065.2,521.078,0,5.20721,4.70306,4.83429,4.61273,2.7356,2.73102,2.05536,1.98303
59999,-114.204,-18.2223,-1331.03,7040.95,-326158,-17800,1059.96,519.71,0,5.24597,4.73969,4.80103,4.58588,2.72125,2.71698,2.03308,1.96259

In [118]:
markers = [name[4:] for name in df_marker.iloc[2].values[0].replace(',,', '').split(',')[:-1]]
cols = [np.repeat(markers, 3), np.tile(['x', 'y', 'z'], len(markers))]
59*3

177

In [119]:
tf = df_marker[0].str.split(',',expand=True).iloc[5:,2:-1]
tf.columns=cols

In [120]:
tf

              RMTPM                                RToeM              \
                  x           y           z            x           y
180015   997.741699  482.071899  126.140205  1036.269531  463.910675
180016  1013.354187  483.400238  121.638397  1052.106201  464.285095
180017  1029.246094  485.030426  117.322807  1069.330322  466.757263
180018  1045.012817  486.362701  113.023087  1086.107422  468.354950
180019  1061.050415  487.984131  108.914856  1102.939819  470.153534
...             ...         ...         ...          ...         ...
192010   868.168640  417.500153  192.753784   892.990112  395.025940
192011   881.364258  418.452179  187.194016   906.543884  395.933929
192012   895.254761  419.024994  181.949615   920.934082  393.660522
192013   909.249634  419.290039  176.644730   939.876587  396.980743
192014   926.536926  418.923950  170.717010   954.398987  396.951111

                          RToe2                                RToeL  ...  \
                 z            x           y           z            x  ...
180015  100.663742  1057.212769  419.811615   94.345665  1001.182434  ...
180016   97.640533  1074.024780  421.391785   91.980202  1017.210815  ...
180017   94.474792  1090.877441  423.048004   89.593895  1033.551514  ...
180018   91.645744  1107.794434  424.640198   87.439751  1049.864868  ...
180019   88.978806  1124.735352  426.427979   85.309998  1066.197388  ...
...            ...          ...         ...         ...          ...  ...
192010  154.673874   909.671753  350.081635  142.053787   866.580566  ...
192011  150.368515   924.808472  350.917847  138.440918   880.219421  ...
192012  146.575775   940.356323  351.667847  134.414993   895.229858  ...
192013  142.759827   955.687988  352.460876  130.180222   909.280579  ...
192014  138.330872   972.385559  353.597382  126.333206   924.572021  ...

            LToe2        LToeL                               LMTPL  \
                z            x           y          z            x
180015  47.189266   926.187500  631.079895  40.807686   874.733154
180016  46.760639   915.200012  631.491821  40.652328   863.688232
180017  46.577545   904.351074  631.902832  40.553642   852.985535
180018  46.970924   893.843323  632.875061  40.628624   842.356812
180019  46.795162   883.232117  633.430115  40.646374   832.057434
...           ...          ...         ...        ...          ...
192010  47.021179  1098.442505  565.833191  41.013706  1044.474365
192011  47.969234  1086.836792  565.848022  41.216824  1032.726440
192012  47.930229  1075.584839  566.043152  41.130192  1021.574707
192013  46.735062  1064.437134  566.090515  41.002934  1010.395630
192014  47.782536  1053.000610  566.257507  41.011917   999.283142

                                     IMULF
                 y          z            x           y           z
180015  647.740906  35.338242   905.488770  591.946106  111.321053
180016  648.167847  36.269753   897.057190  592.322571  111.542709
180017  647.321350  37.065811   889.020203  593.705688  112.295700
180018  648.311890  38.956886   881.102539  594.838257  113.492523
180019  648.153625  40.164345   873.078552  596.229370  114.757492
...            ...        ...          ...         ...         ...
192010  581.718262  30.480650  1055.167358  516.570801  105.573059
192011  582.344116  30.136024  1045.686035  517.374268  106.057716
192012  582.445984  30.130182  1035.663940  518.796753  106.280022
192013  582.624146  30.340557  1026.054443  519.750305  106.547379
192014  582.812256  30.516121  1016.751892  520.823608  107.208397

[12000 rows x 177 columns]

In [72]:
cols_imu = df_imu.iloc[3].values[0].split(',')

In [73]:
cols_imu

['Frame',
 'Sub Frame',
 'IMU1_ACC_X',
 'IMU1_ACC_Y',
 'IMU1_ACC_Z',
 'IMU2_ACC_X',
 'IMU2_ACC_Y',
 'IMU2_ACC_Z',
 'IMU3_ACC_X',
 'IMU3_ACC_Y',
 'IMU3_ACC_Z',
 'IMU4_ACC_X',
 'IMU4_ACC_Y',
 'IMU4_ACC_Z',
 'IMU5_ACC_X',
 'IMU5_ACC_Y',
 'IMU5_ACC_Z',
 'IMU6_ACC_X',
 'IMU6_ACC_Y',
 'IMU6_ACC_Z',
 'IMU7_ACC_X',
 'IMU7_ACC_Y',
 'IMU7_ACC_Z',
 'IMU8_ACC_X',
 'IMU8_ACC_Y',
 'IMU8_ACC_Z',
 'IMU9_ACC_X',
 'IMU9_ACC_Y',
 'IMU9_ACC_Z',
 'IMU10_ACC_X',
 'IMU10_ACC_Y',
 'IMU10_ACC_Z',
 'IMU11_ACC_X',
 'IMU11_ACC_Y',
 'IMU11_ACC_Z',
 'IMU12_ACC_X',
 'IMU12_ACC_Y',
 'IMU12_ACC_Z',
 'IMU13_ACC_X',
 'IMU13_ACC_Y',
 'IMU13_ACC_Z',
 'IMU14_ACC_X',
 'IMU14_ACC_Y',
 'IMU14_ACC_Z',
 'IMU15_ACC_X',
 'IMU15_ACC_Y',
 'IMU15_ACC_Z',
 'IMU16_ACC_X',
 'IMU16_ACC_Y',
 'IMU16_ACC_Z',
 'IMU1_GYR_X',
 'IMU1_GYR_Y',
 'IMU1_GYR_Z',
 'IMU2_GYR_X',
 'IMU2_GYR_Y',
 'IMU2_GYR_Z',
 'IMU3_GYR_X',
 'IMU3_GYR_Y',
 'IMU3_GYR_Z',
 'IMU4_GYR_X',
 'IMU4_GYR_Y',
 'IMU4_GYR_Z',
 'IMU5_GYR_X',
 'IMU5_GYR_Y',
 'IMU5_GYR_Z',
 'IMU6_GYR_X',
 'IMU6_GYR_Y',
 'IMU6_GYR_Z',
 'IMU7_GYR_X',
 'IMU7_GYR_Y',
 'IMU7_GYR_Z',
 'IMU8_GYR_X',
 'IMU8_GYR_Y',
 'IMU8_GYR_Z',
 'IMU9_GYR_X',
 'IMU9_GYR_Y',
 'IMU9_GYR_Z',
 'IMU10_GYR_X',
 'IMU10_GYR_Y',
 'IMU10_GYR_Z',
 'IMU11_GYR_X',
 'IMU11_GYR_Y',
 'IMU11_GYR_Z',
 'IMU12_GYR_X',
 'IMU12_GYR_Y',
 'IMU12_GYR_Z',
 'IMU13_GYR_X',
 'IMU13_GYR_Y',
 'IMU13_GYR_Z',
 'IMU14_GYR_X',
 'IMU14_GYR_Y',
 'IMU14_GYR_Z',
 'IMU15_GYR_X',
 'IMU15_GYR_Y',
 'IMU15_GYR_Z',
 'IMU16_GYR_X',
 'IMU16_GYR_Y',
 'IMU16_GYR_Z']

In [74]:
df_imu = df_imu[0].str.split(',',expand=True).iloc[5:,:-1]

In [75]:
df_imu.columns=cols_imu

In [79]:
df_imu.reset_index(drop=True, inplace=True)

In [80]:
df_imu

,Frame,Sub Frame,IMU1_ACC_X,IMU1_ACC_Y,IMU1_ACC_Z,IMU2_ACC_X,IMU2_ACC_Y,IMU2_ACC_Z,IMU3_ACC_X,IMU3_ACC_Y,...,IMU13_GYR_Z,IMU14_GYR_X,IMU14_GYR_Y,IMU14_GYR_Z,IMU15_GYR_X,IMU15_GYR_Y,IMU15_GYR_Z,IMU16_GYR_X,IMU16_GYR_Y,IMU16_GYR_Z
0,1,0,9.98223,-91.4154,9862.16,-6.79949,-61.4365,9722.13,-11.9915,51.0846,...,0,-25.5323,401.324,2.99266,146.107,-108.229,184.101,0.223666,-0.111833,0.228786
1,1,1,10.6325,-92.0657,9853.05,-10.0511,-52.3321,9734.49,-15.8934,48.4833,...,0,-25.1677,400.247,2.20545,143.613,-100.837,183.529,0.19052,-0.0952602,0.203927
2,1,2,11.2829,-92.716,9843.95,-13.3026,-43.2277,9746.84,-19.7953,45.8821,...,0,-24.8031,399.17,1.41825,141.119,-93.446,182.957,0.157375,-0.0786874,0.179068
3,1,3,11.9332,-93.3663,9834.84,-16.5542,-34.1233,9759.2,-23.6972,43.2808,...,0,-24.4385,398.092,0.631042,138.625,-86.0545,182.385,0.124229,-0.0621147,0.154209
4,1,4,12.5835,-94.0166,9825.74,-19.8058,-25.0189,9771.55,-27.5991,40.6796,...,0,-24.0739,397.015,-0.156162,136.13,-78.6631,181.813,0.091084,-0.045542,0.12935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,12000,5,37.7405,-123.196,9796.35,31.9264,-2.8603,9829.39,14.5331,32.6009,...,-0.0471108,-0.613632,372.953,-27.7582,-81.0461,-1.55895,206.254,0.0278523,0.061037,0.20237
119996,12000,6,30.5524,-125.107,9794.12,40.4152,1.93346,9807.11,19.6034,40.7383,...,-0.0492379,-0.557534,374.953,-27.1618,-83.698,-9.99148,206.981,0.0143596,0.0579575,0.21491
119997,12000,7,33.4322,-117.178,9782.88,38.4206,5.68215,9792.92,16.2536,44.334,...,-0.038306,-0.556489,377.069,-26.4896,-86.5863,-22.3543,207.853,0.0113655,0.0496715,0.198686
119998,12000,8,43.8372,-104.822,9769.87,28.0156,6.33246,9794.22,7.1492,41.7327,...,-0.0217333,-0.606207,378.08,-26.1333,-88.0364,-31.2207,208.358,0.0196519,0.0413851,0.165541
119999,12000,9,54.2422,-92.4659,9756.87,17.6105,6.98278,9795.52,-1.95519,39.1315,...,-0.00516054,-0.655926,379.091,-25.777,-89.4865,-40.0871,208.864,0.0279382,0.0330988,0.132395

In [68]:
df_imu

,index,Frame,Sub Frame,IMU1_ACC_X,IMU1_ACC_Y,IMU1_ACC_Z,IMU2_ACC_X,IMU2_ACC_Y,IMU2_ACC_Z,IMU3_ACC_X,...,IMU13_GYR_Z,IMU14_GYR_X,IMU14_GYR_Y,IMU14_GYR_Z,IMU15_GYR_X,IMU15_GYR_Y,IMU15_GYR_Z,IMU16_GYR_X,IMU16_GYR_Y,IMU16_GYR_Z
0,5,1,0,9.98223,-91.4154,9862.16,-6.79949,-61.4365,9722.13,-11.9915,...,0,-25.5323,401.324,2.99266,146.107,-108.229,184.101,0.223666,-0.111833,0.228786
1,6,1,1,10.6325,-92.0657,9853.05,-10.0511,-52.3321,9734.49,-15.8934,...,0,-25.1677,400.247,2.20545,143.613,-100.837,183.529,0.19052,-0.0952602,0.203927
2,7,1,2,11.2829,-92.716,9843.95,-13.3026,-43.2277,9746.84,-19.7953,...,0,-24.8031,399.17,1.41825,141.119,-93.446,182.957,0.157375,-0.0786874,0.179068
3,8,1,3,11.9332,-93.3663,9834.84,-16.5542,-34.1233,9759.2,-23.6972,...,0,-24.4385,398.092,0.631042,138.625,-86.0545,182.385,0.124229,-0.0621147,0.154209
4,9,1,4,12.5835,-94.0166,9825.74,-19.8058,-25.0189,9771.55,-27.5991,...,0,-24.0739,397.015,-0.156162,136.13,-78.6631,181.813,0.091084,-0.045542,0.12935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,120000,12000,5,37.7405,-123.196,9796.35,31.9264,-2.8603,9829.39,14.5331,...,-0.0471108,-0.613632,372.953,-27.7582,-81.0461,-1.55895,206.254,0.0278523,0.061037,0.20237
119996,120001,12000,6,30.5524,-125.107,9794.12,40.4152,1.93346,9807.11,19.6034,...,-0.0492379,-0.557534,374.953,-27.1618,-83.698,-9.99148,206.981,0.0143596,0.0579575,0.21491
119997,120002,12000,7,33.4322,-117.178,9782.88,38.4206,5.68215,9792.92,16.2536,...,-0.038306,-0.556489,377.069,-26.4896,-86.5863,-22.3543,207.853,0.0113655,0.0496715,0.198686
119998,120003,12000,8,43.8372,-104.822,9769.87,28.0156,6.33246,9794.22,7.1492,...,-0.0217333,-0.606207,378.08,-26.1333,-88.0364,-31.2207,208.358,0.0196519,0.0413851,0.165541
119999,120004,12000,9,54.2422,-92.4659,9756.87,17.6105,6.98278,9795.52,-1.95519,...,-0.00516054,-0.655926,379.091,-25.777,-89.4865,-40.0871,208.864,0.0279382,0.0330988,0.132395